Get Category with Plates. Modify format in a few files. Add imageId in CategoryMapper methods.
PabloProgramming/eoeats pull request #12
Opened 2024-06-16 09:22 UTC by PabloProgramming

2024-06-16 20:04 UTC, TomyQB requested changes

2024-06-16 20:04 UTC, TomyQB commented on src/main/java/com/app/eoeats/service/mapper/CategoryMapper.java
> +                .platesByCategory(platesResponseMapper.PlatesToPlatesDto(category.getPlates()))
Método en mayúsculas 😅

2024-06-16 20:04 UTC, TomyQB commented on src/main/java/com/app/eoeats/service/mapper/PlatesResponseMapper.java
> +            if (plate != null) {
No hace falta esta comprobación

2024-06-17 21:33 UTC, PabloProgramming commented on src/main/java/com/app/eoeats/service/mapper/CategoryMapper.java
> +                .platesByCategory(platesResponseMapper.PlatesToPlatesDto(category.getPlates()))
joe, sorry :)

2024-06-24 11:39 UTC, TomyQB approved these changes

2024-06-24 16:41 UTC, merged